### PR TITLE
change ibo-Connector to the new structure.

### PR DESCRIPTION
**Pull request by OoDivmasteroO**

### CODE REVIEW

**Comment by romansmirnov** [comment]
Hi,

Thank you for your pull request.

I created therefore a task (see [1](https://app.camunda.com/jira/browse/CAM-3910)).

Cheers,
Roman

**Comment by meyerdan** [comment]
Hi @OoDivmasteroO ,

are you a developer at IBO?

Regards,
Daniel

**Comment by OoDivmasteroO** [comment]
Hi,

@romansmirnov Thank you for creating the task.
@meyerdan  Yes, I am a developer of ibo.

Regards,
David

**Comment by meyerdan** [comment]
Hi David,

I now gave you push access to this repository since you are the maintainer.

**Pull request closed without merging**
